[tool.poetry]
name = "dfmt"
version = "0.1.0"
description = ""
authors = ["Dimitri Merejkowsky <d.merej@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
dfmt = "dfmt:main"
